### PR TITLE
change confirm text

### LINKED ISSUE #154: Improve text in "Summary" step of single publication/dataset workflow
**Describe the improvement**
Replace "Next steps" with "Are you ready to publish?"

When you are not ready to publish, you can save your dataset/publication as draft using the "Save as draft" button and continue later from Overview page. Alternatively, you can click on one of the sections below to complete your submission.

When you are ready to publish, click the "Publish to Biblio" button. Your dataset/publication will be available in Biblio. The dataset/publication will undergo a bibliographic review process by the Biblio team. A reviewer of the Biblio team will contact you in case any changes are needed.

### PR DESCRIPTION
**Pull request by nicolasfranck**
Fixes #154

### CODE REVIEW

**Review by nics — CHANGES_REQUESTED** [review]
Your dataset will be reviewed by Biblio first, once it has been validated it will become public in Biblio.

Die zin moet ook anders cfr. publications

**Comment by nics** [comment]
ik ga hier gewoon het ontwerp blijven volgen

**Comment by sdebodt** [comment]
@nics , do you mean that you will keep the text "Your dataset will be reviewed by Biblio first, once it has been validated it will become public in Biblio."

This is not correct as it is public in Biblio before validation by the reviewer.

**Comment by nics** [comment]
no i mean keeping the "Next steps" text, that were the only changes in the pr

**Pull request closed without merging**
